services:
  judgehost-0:
    env_file:
      - domjudge.env
    container_name: judgehost-0
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-0
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - domjudge
    environment:
      - CONTAINER_TIMEZONE=Asia/Seoul
      - JUDGEDAEMON_USERNAME=judgehost
      - DAEMON_ID=0
      - JUDGEDAEMON_PASSWORD=${RESTAPI_PASSWORD}

  judgehost-1:
    container_name: judgehost-1
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - domjudge
    environment:
      - CONTAINER_TIMEZONE=Asia/Seoul
      - JUDGEDAEMON_USERNAME=judgehost
      - DAEMON_ID=1
      - JUDGEDAEMON_PASSWORD=${RESTAPI_PASSWORD}

networks:
  domjudge:
    external: true